AWS_ACCESS_KEY_ID: AKIAIES4QGG7FBZT6W2A
AWS_SECRET_ACCESS_KEY: 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
development:
  AWS_BUCKET: beardwars
production:
  AWS_BUCKET: beardwars
S3_BUCKET_NAME: beardwars
AWS_REGION: us-east-1
